---
- name: Fedora host
  hosts: invexClevo
  become: true
  pre_tasks:
    # - debug:
    #     var: hostvars[inventory_hostname]
  roles:
    - servers/network-static-dns
    - servers/network-bridge
    - servers/libvirt
